[project]
name = "qr-generator"
version = "0.1.0"
description = "User-friendly web interface for generating QR codes"
requires-python = ">=3.13"
dependencies = [
    "qrcode[pil]>=8.2",
    "flask>=2.0.0",
]
